title: Race UP Electric Division
email: info@raceup.it
description: Race UP ED is the Electric Division of the FSAE team of the University of Padova. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: RaceUpTeam
github_username: raceup

# Build settings
markdown: kramdown
